Repository Skatteetaten/terraform-nomad-trino, pull requests merged in 2020-09, with the labels that each got.

#6 Sync template origin
  LICENSE
  Makefile
  README_template.md
  Vagrantfile
  Vagrantfile.default
  dev/ansible/README.md
  dev/vagrant/conf/README.md
  dev/vagrant/conf/consul/README.md
  dev/vagrant/conf/nomad/README.md
  dev/vagrant/conf/pre_bootstrap/README.md
  dev/vagrant/conf/vault/README.md
  docker/README.md
  example/README.md
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/01-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/02-poststart-example.yml
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/01-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/02-prestart-example.yml
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/main.tf
  template_example/example/nomad_acl_test.tf
  template_example/example/variables.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
Labels: documentation, enhancement

#11 Fix linter version; update CHANGELOG.md
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: bug

#9 Documentation header update
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  README.md
  dev/ansible/05_presto_create_tables.yml
  example/resources/data/README.md
Labels: documentation

#13 Multi node connect
  Makefile
  README.md
  conf/nomad/README.md
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
  dev/ansible/01_build_presto_cli_image.yml
  dev/ansible/05_presto_create_tables.yml
  docker/Dockerfile.presto-cli
  docker/README.md
  example/main.tf
  main.tf
  outputs.tf
  variables.tf
Labels: enhancement

#21 Use docker for everything. #17
  Makefile
  README.md
Labels: enhancement

#19 Move certificates handling into the server.
  conf/nomad/presto.hcl
Labels: enhancement

#20 fix repeating keys in ansible.
  dev/ansible/05_presto_create_tables.yml
Labels: enhancement
