Repository Skatteetaten/terraform-nomad-trino, pull requests merged in 2020-11, with the labels that each got.

#63 Fix broken path `make clean`
  Makefile
Labels: skip-changelog

#68 Add json flattened example
  CHANGELOG.md
  README.md
  dev/ansible/05_presto_create_tables.yml
  example/resources/data/README.md
  example/resources/query/flattenedjson_json.sql
Labels: type/documentation, type/enhancement

#71 Added CPU as user-defined variable
  CHANGELOG.md
  README.md
  conf/nomad/presto.hcl
  main.tf
  variables.tf
Labels: type/enhancement

#70 Credentials & updated box version & fixed make warning
  CHANGELOG.md
  Makefile
  README.md
  Vagrantfile.default
  conf/nomad/presto.hcl
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  example/presto_cluster/main.tf
  example/presto_cluster/providers.tf
  main.tf
  variables.tf
Labels: type/bug, type/documentation, type/enhancement

#72 Updated documentation
  CHANGELOG.md
  Makefile
  README.md
  dev/vagrant/bootstrap/vault/post/01-create-vault-policy-to-read-secrets.yml
Labels: type/documentation

#76 Removed slashes in template paths
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
Labels: skip-changelog

#79 Issues 77, 73 & 46 ++
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
  dev/ansible/00_generate_secrets_vault.yml
  dev/vagrant/bootstrap/vault/post/01-create-vault-policy-to-read-secrets.yml
  example/presto_cluster/main.tf
  example/presto_standalone/main.tf
  main.tf
  variables.tf
Labels: type/documentation, type/enhancement

#86 Re-added test & one new
  CHANGELOG.md
  conf/nomad/presto_standalone.hcl
  dev/vagrant/bootstrap/vault/post/01-create-vault-policy-to-read-secrets.yml
Labels: theme/test, type/enhancement

#88 Release 0.3.0
  CHANGELOG.md
Labels: minor

#87 Improve credentials management - [Vault provided]
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/README.md
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
  dev/ansible/00_generate_secrets_vault.yml
  dev/ansible/03_upload_files.yml
  dev/ansible/README.md
  dev/vagrant/bootstrap/vault/post/01-create-vault-policy-to-read-secrets.yml
  example/presto_cluster/README.md
  example/presto_cluster/main.tf
  example/presto_standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#91 Add variable `hive_config_properties` for custom hive configuration properties
  CHANGELOG.md
  README.md
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
  example/presto_standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#94 release 0.3.1
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  example/presto_cluster/main.tf
  example/presto_standalone/main.tf
Labels: patch
