Repository Skatteetaten/terraform-nomad-trino, pull requests merged in 2020-10, with the labels that each got.

#35 code to support consul acl deny config
  CHANGELOG.md
  Makefile
  dev/ansible/01_create_intention.yml
  dev/ansible/03_upload_files.yml
  dev/ansible/05_presto_create_tables.yml
  example/main.tf
Labels: bug

#31 Presto connect plugin uri
  CHANGELOG.md
  README.md
  conf/nomad/presto.hcl
  main.tf
  variables.tf
Labels: enhancement

#36 Added random secret (in vault) for presto cluster communication
  CHANGELOG.md
  README.md
  Vagrantfile.default
  conf/nomad/presto.hcl
  dev/ansible/00_generate_secrets_vault.yml
  dev/vagrant/conf/nomad/00-enable-vault.hcl
  dev/vagrant/conf/post_bootstrap/01-create-vault-policy-to-read-secrets.yml
  example/README.md
  example/main.tf
  example/variables.tf
  main.tf
  variables.tf
Labels: enhancement

#37 Added canary switch
  CHANGELOG.md
  README.md
  conf/nomad/presto.hcl
  conf/nomad/presto_standalone.hcl
  example/main.tf
  main.tf
  variables.tf
Labels: enhancement

#38 bump versions
  CHANGELOG.md
  example/main.tf
Labels: enhancement

#39 release_0.1.0
  CHANGELOG.md
Labels: minor

#44 Added github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#50 Updated input section in readme
  CHANGELOG.md
  README.md
Labels: type/documentation

#55 Updated depending modules, updated documentation
  .gitignore
  CHANGELOG.md
  README.md
  dev/ansible/01_create_intention.yml
  dev/ansible/02_run_terraform.yml
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  dev/vagrant/bootstrap/nomad/post/host_volume_policy.hcl
  dev/vagrant/bootstrap/nomad/pre/00-create_dir_for_persisting_data.yml
  dev/vagrant/conf/nomad/99-mount-host-volume.hcl
  example/README.md
  example/presto_cluster/README.md
  example/presto_cluster/main.tf
  example/presto_cluster/providers.tf
  example/presto_cluster/terraform-nomad-presto.png
  example/presto_cluster/variables.tf
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  example/vagrant_box_example/nomad_acl.tf
Labels: type/documentation, type/enhancement

#59 Release 0.2.0
  CHANGELOG.md
Labels: minor
